server.port=8080
nextoffer.admin.email=${NEXTOFFER_ADMIN_EMAIL:}
nextoffer.admin.password=${NEXTOFFER_ADMIN_PASSWORD:}
server.error.include-message=always
server.error.include-stacktrace=always
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=NextOfferDB;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=Spring@123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
logging.level.org.springframework.web=DEBUG
logging.level.org.thymeleaf=TRACE
spring.thymeleaf.cache=false
